### PR TITLE
Fix support for relative imports

### PR DESCRIPTION
**Pull request by embray**
If a module in a package used relative imports, it couldn't be imported properly.

This fix handles the case the same way pytest does.  Depends on #6 since everything is broken without it.

@lgpage P.S. if you don't have time to maintain this package anymore I'm happy to help e.g. merge PRs and create new releases, if you don't mind adding me as a maintainer.  I might also try to get some of the functionality from this plugin merged upstream into pytest (esp. loading doctests from extension modules).  Either way, thanks for the plugin!

### CODE REVIEW

**Comment by lgpage** [comment]
@embray thank you for this and for offering to help maintain this plugin, I will take you up on that offer :)
When you get a chance please resolve the conflict from me merging #6

**Comment by lgpage** [comment]
@embray I was looking at the pytest code a bit and see it has changed quite a bit and agree the importing of extension modules needs to be merged upstream to avoid having to keep copying code across and monkey patching it :P

**Comment by embray** [comment]
@lgpage And thanks for accepting the offer!  This plugin really helped me and I'd like to help it along.  BTW can you please resend the PyPI invitation?  I was too late in getting around to my e-mail and it expired.

**Comment by lgpage** [comment]
@embray PyPI invitation resent

**Pull request merged**
