### PR TITLE
Fix deprecated

### LINKED ISSUE #3: Depreciation warnings
Running `pytest --doctest-cython` works, but gives the following warnings
```
<some_path>/python3.7/site-packages/pytest_cython/plugin.py:70
  <some_path>/python3.7/site-packages/pytest_cython/plugin.py:70: PytestDeprecationWarning: direct construction of DoctestModule has been deprecated, please use DoctestModule.from_parent
    return DoctestModule(path, parent)

<some_path>/.local/lib/python3.7/site-packages/pytest_cython/plugin.py:120
<some_path>/.local/lib/python3.7/site-packages/pytest_cython/plugin.py:120
  <some_path>/.local/lib/python3.7/site-packages/pytest_cython/plugin.py:120: PytestDeprecationWarning: direct construction of DoctestItem has been deprecated, please use DoctestItem.from_parent
    yield DoctestItem(test.name, self, runner, test)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

## A Quick Workaround
```bash
pytest --doctest-cython --disable-warnings
```

# Info
* OS: Fedora 31 (Thirty One) x86_64
* Sample `fib.pyx`

```python3
#cython: language_level=3

def fib(int n):
    '''Return the nth number in the Fibonacci sequence.

    >>> fib(0)
    0.0
    >>> fib(1)
    1.0
    >>> fib(4)
    3.0
    >>> fib(7)
    13.0
    '''
    cdef int i
    cdef double a=0.0, b=1.0
    for i in range(n):
        a, b = a + b, a
    return a
```

### PR DESCRIPTION
**Pull request by thrasibule**
Fixes #3

### CODE REVIEW

**Review by anthrotype — APPROVED** [review]

**Comment by lgpage** [comment]
Thank you @thrasibule and @anthrotype, much appreciated

**Comment by anthrotype** [comment]
thanks @thrasibule for the fix, and also thanks @lgpage for merging this!
Will you be able to publish a new release of pytest-cython with this fix sometime soon? 🙇

**Comment by anthrotype** [comment]
@lgpage Hello! Could you please upload an updated release to PyPI with this fix? 🙏

**Comment by lgpage** [comment]
@anthrotype apologies for the delay. I will try get this released to PyPI once #7 is merged

**Pull request merged**
